### ISSUE TITLE
Code Improvement checklist

### ISSUE THREAD

**Issue by Sanjeevsetu** [SuperPWA/Super-Progressive-Web-Apps#486]
- [x] Escaping missing 3rd-party\wonderpush.php Line : 101, 112, 
- [x] check sprintf path 3rd-party\onesignal.php
- [x] escaping missing path 3rd-party\amp.php Line: 72, 79, 
- [x] Remove unused variable. Check if var $arrayOPT is used across the plugin. if not delete it
- [x] Escaping missing path addons\caching-strategies.php Line : 303,304,305,306,307,308 
- [x] Replace all json_encode with wp_json_encode and escap all static response strings 
- [x] Escaping missing path addons\apple-touch-icons.php Line : 48, 49, 58, 400
- [x] Wrong escaping function used path addons\apple-touch-icons.php Line : 190
- [x] All text domains for translation text inside \admin\deactivate-feedback.php file is wrong. 
- [x] Remove all commented code across the files
- [x] variable validation before used inside strpos path \admin\admin-ui-setup.php Line : 637
- [x] escaping missing path admin\admin-ui-render-upgrade.php Line: 20, 68, 81,87,94, 102, 110, 117, 124, 230, 
- [x] escaping missing path admin\admin-ui-render-settings.php Line: 506, 510, 753, 819
- [x] escaping missing path public\manifest.php. Line: 283, 276, 277, 370
- [x] escaping missing path admin\basic-setup.php Line: 373, 381, 382
- [x] escaping missing path admin\deactivate-feedback.php Line: 78
- [x] html tags not to be there path admin\deactivate-feedback.php Line: 312, 330, 338, 346, 
- [x] exploded/loop variable validation missing path public\manifest.php. Line: 402, 362, 485, 464
- [x] sanitization missing path admin\admin-ui-render-addons.php Line : 232, 587, 607, 613, 649, 656, 659
- [x] Replace _e( with esc_html_e. Actually _e only Displays translated text but esc_html_e does safe escaping and keep all html tags outside from these functions
- [x] discuss funciton 'superpwa_license_expire_warning' and 'superpwa_amp_manifest_json_relink' with @Sanjeevsetu

**Comment by akshaywali** [comment]
pushed in version 2.2.23
